apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: docker-run
spec:
  workspaces:
    - name: workspace
  params:
    - name: dockerfile
      description: Content of Dockerfile
      default: "IyBVc2UgdGhlIG9mZmljaWFsIFVidW50dSAyMi4wNCBpbWFnZSBhcyB0aGUgYmFzZSBpbWFnZQpGUk9NIHVtZXNoMTIxMi9kcnVwYWwtYmFzZTpsYXRlc3QKCiMgU2V0IHRoZSB3b3JraW5nIGRpcmVjdG9yeQpXT1JLRElSIC92YXIvd3d3L2h0bWwKCiMgQ29weSBhcHBsaWNhdGlvbiBmaWxlcyB0byB0aGUgd29ya2luZyBkaXJlY3RvcnkKQ09QWSAtLWNob3duPXd3dy1kYXRhOnd3dy1kYXRhIC4gLgoKIyBFbnN1cmUgLmVudiBmaWxlIGV4aXN0cwpSVU4gdG91Y2ggLmVudgoKIyBSdW4gY29tcG9zZXIgaW5zdGFsbCBpZiBjb21wb3Nlci5qc29uIGlzIHByZXNlbnQKUlVOIGlmIFsgLWYgY29tcG9zZXIuanNvbiBdOyB0aGVuIGNvbXBvc2VyIGluc3RhbGw7IGZpCgojIEV4cG9zZSBwb3J0IDgwCkVYUE9TRSA4MAoKIyBTdGFydCBQSFAgYnVpbHQtaW4gc2VydmVyCkNNRCBbInBocCIsICItUyIsICIwLjAuMC4wOjgwIl0K"
      type: string
    - name: dockerignore
      description: Content of Docker Ignore
      default: ".git"
      type: string 
    - name: docker_user
      description: Docker User
      default: "umesh1212"
      type: string
    - name: docker_token
      description: Docker dockerToken  
      default: "dckr_pat_pnyzNT9yR5NlfrIzmn9Wtj8XLmo"
      type: string
    - name: docker_service
      description: Path to service
      default: "docker.io"
      type: string
    - name: base_image
      description: Path to base image
      default: base image
      type: string 
    - name: base_tag
      description: Path to base tag
      default: base tag
      type: string
    - name: destination
      description: Destination path
      default: umesh1212/drupal-test123
  steps:
    - name: build
      image: docker
      env:
        - name: "DOCKER_USER"
          value: "umesh1212"
        - name: "DOCKER_TOKEN"
          value: "dckr_pat_pnyzNT9yR5NlfrIzmn9Wtj8XLmo
        - name: "DOCKER_SERVICE"
          value: "$(params.docker_service)"
        - name: DOCKER_FILE
          value: "$(params.dockerfile)"
        - name: DOCKER_IGNORE
          value: "$(params.dockerignore)"
        - name: DOCKER_URL
          value: "$(params.destination)"
        - name: BASE_IMAGE
          value: "$(params.base_image)"
        - name: BASE_TAG
          value: "$(params.base_tag)"
      script: |
        #!/bin/sh
        cd /workspace/workspace/
        until docker ps; do sleep 3; done;
        #echo "$(params.dockerfile)" > Dockerfile;
        echo "$DOCKER_FILE" | base64 -d > Dockerfile;
        if [[ ! -z "$DOCKER_IGNORE" ]] && [[ ! -f ".dockerignore" ]]; then echo "${DOCKER_IGNORE}" > .dockerignore; fi
        docker build . -t "${DOCKER_URL}" || exit 1
        echo "Successfully built"
      volumeMounts:
      - mountPath: /var/run/
        name: dind-socket
      - mountPath: /var/lib/docker
        name: dind-storage
    - name: push
      image: docker
      env:
        - name: "DOCKER_USER"
          value: "$(params.docker_user)"
        - name: "DOCKER_TOKEN"
          value: "$(params.docker_token)"
        - name: "DOCKER_SERVICE"
          value: "$(params.docker_service)"
        - name: DOCKER_FILE
          value: "$(params.dockerfile)"
        - name: DOCKER_IGNORE
          value: "$(params.dockerignore)"
        - name: DOCKER_URL
          value: "$(params.destination)"
        - name: BASE_IMAGE
          value: "$(params.base_image)"
        - name: BASE_TAG
          value: "$(params.base_tag)"
      script: |
        #!/bin/sh
        cd /workspace/workspace/
        until docker ps; do sleep 3; done;
        docker login -u "${DOCKER_USER}" -p "${DOCKER_TOKEN}" "${DOCKER_SERVICE}" 2>/dev/null || exit 1
        docker push "${DOCKER_URL}" || exit 1
        echo "Successfully pushed"
      volumeMounts:
      - mountPath: /var/run/
        name: dind-socket
      - mountPath: /var/lib/docker
        name: dind-storage
  sidecars:
    - image: docker:20.10-dind
      name: server
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/docker
          name: dind-storage
        - mountPath: /var/run/
          name: dind-socket
  volumes:
    - name: dind-storage
      emptyDir: {}
    - name: dind-socket
      emptyDir: {}