apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: docker-run
spec:
  workspaces:
    - name: workspace
  steps:
    - name: docker-run
      image: docker
      script: |
        #!/bin/sh
        ls -al /var/www/html/
        mkdir -p /app
        cd /app
        until docker ps; do sleep 3; done;
        printf "from ubuntu:18.04\nrun apt-get update\nrun apt-get install -y curl\nrun curl -s google.com\ncmd curl -s https://www.google.com" > Dockerfile
        echo "Successfully build image"
        echo "Completed"
      volumeMounts:
      - mountPath: /var/run/
        name: dind-socket
  sidecars:
    - image: docker:18.05-dind
      name: server
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/docker
          name: dind-storage
        - mountPath: /var/run/
          name: dind-socket
  volumes:
    - name: dind-storage
      emptyDir: {}
    - name: dind-socket
      emptyDir: {}