apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: docker-run
spec:
  workspaces:
    - name: workspace
  steps:
    - name: docker-run
      image: docker
      script: |
        #!/bin/sh
        ls -al /var/www/html/
        until docker ps; do sleep 3; done;
        printf "FROM umesh1212/drupal-base:latest\nWORKDIR /var/www/html\nCOPY --chown=www-data:www-data . .\nRUN touch .env && if [ -f composer.json ]; then composer install; fi\nEXPOSE 80\nCMD [\"php\", \"-S\", \"0.0.0.0:80\"]" > Dockerfile
        docker build . -t google
        echo "Successfully build image"
        echo "Completed"
      volumeMounts:
      - mountPath: /var/run/
        name: dind-socket
  sidecars:
    - image: docker:18.05-dind
      name: server
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/docker
          name: dind-storage
        - mountPath: /var/run/
          name: dind-socket
  volumes:
    - name: dind-storage
      emptyDir: {}
    - name: dind-socket
      emptyDir: {}